### ISSUE TITLE
#7 Page for starting the game and access to action item list

### ISSUE THREAD

**Issue by gaborrubus** [gaborrubus/capstone-project#10]
## Value proposition

As a user 
I want to see a page for starting the game with a setting button that leads to the action item list and a play button that leads to the wheel 
in order to be able to access the action items, respectively be able to play the game

## Description

![image](https://user-images.githubusercontent.com/125888791/233659955-42b3821f-a920-4fe1-abc3-88ef8200e195.png)

![image](https://user-images.githubusercontent.com/125888791/233660319-0a744a9f-3455-4952-8c2d-ed06b9320557.png)

## Acceptance criteria

- [ ] There is a button at the top area of the screen to access the action item list.
- [ ] There is a game-related picture in the middle 
- [ ] There is a play button on the lower half of the picture that leads to the playing field.

- [ ] There is a back button at the action item list page

## Tasks

- [ ] Creating "gear wheel icon" as a button for settings, that leads to the action item list.
- [ ] Inserting sample picture.
- [ ] Creating play button, that leads to the wheel page.

- [ ] Creating a back button at the action item list page.

Size: S
