### ISSUE TITLE
#2 Create an action Item 

### ISSUE THREAD

**Issue by gaborrubus** [gaborrubus/capstone-project#4]
## Value proposition

As a user
I want to see the page to add action items
in order to be able to add later items to the list

## Description
![image](https://user-images.githubusercontent.com/125888791/233290054-852eb1c0-9ea1-408c-83f2-c7a1f73bfb1a.png)

## Acceptance criteria

- [ ] I see the field for the question number
- [ ] I see a grey placeholder for the picture 
- [ ] I see a field for the points
- [ ] I see a field for the description

## Tasks

- [ ] create the form component CreateActivity
- [ ] create the required fields and the picture placeholder
- [ ] create the greyed out description box text for explanatory reasons.

Size: M
