### ISSUE TITLE
#3 [id] page 

### ISSUE THREAD

**Issue by gaborrubus** [gaborrubus/capstone-project#5]
## Value proposition

As a user 
I want to see an Action Item page 
in order to be able to see the individual action item with all it#s elements 

## Description

![image](https://user-images.githubusercontent.com/125888791/233292887-0ed15683-e7b6-4ba2-b204-be22e43ba2eb.png)

## Acceptance criteria

- [ ] See the action item number, picture, 
- [ ] See the point for the action and the description

## Tasks

- [ ] Research for pictures and ideas
- [ ] Create an Document for the point system 
- [ ] Create a description of the action items for later use
- [ ] Create the item number, placeholder picture 
- [ ] Create the points and description

Size: L

**Comment by BenRodProd** [comment]
I would say this could be the 2nd user story, because displaying the details after clicking on an item on the list is connected and leaves a functional app...
