### ISSUE TITLE
Board syling

### ISSUE THREAD

**Issue by gaborrubus** [gaborrubus/capstone-project#6]
## Value proposition

As a user 
I want to see a board with a start/end field plus as many numbered fields as actions are
in order to be able to use this board later as a playing field

## Description

![image](https://user-images.githubusercontent.com/125888791/233303188-822cc705-629c-46a9-86f7-1ee7a76cc67f.png)

## Acceptance criteria

- [ ] There is a start/end field 
- [ ] There are as many numbered fields as actions 

## Tasks

- [ ] create the AbtionBoard component 
- [ ] create the start/end field 
- [ ]  create the numbered field 
- [ ] use styled component to style it

Size: L

**Comment by CJAkkuec** [comment]
The design of the board as it stands right now may be a little challenging to implement, so I agree with the size of the User Story.

>  There is a start/end field
>  There are as many numbered fields as actions

I think you may not be thinking this all the way through.
What data is the number of actions derived from? If you're stating "as many as", then we're deriving information from somewhere.
At this point I would probably implement a set of dummy actions that determine the amount of actions.

Something like:
```
[
{playerID: "ssadasfq3r423897523940r",
action: "going for a walk"},
{playerID: "ssdssfq3r424353457523940r",
action: "eating french fries"},
{playerID: "ssdssfsdfsd353457523940r",
action: "petting a bunny"},
//etc ...
]
```

You may also question whether you need a start/end field. What is it for? What is the desired behavior?

>  create the AbtionBoard component
>  create the start/end field
>  create the numbered field
>  use styled component to style it

*ActionBoard ;)
Strictly speaking, you don't create the numbered field yourself. (Or rather, I wouldn't recommend it.) You would probably inform the ActionBoard component about the number of fields it needs to divide itself into.

There isn't anything wrong with this User Story per se, I'd probably only suggest you think about it a little more.

**Comment by gaborrubus** [comment]
So I have redesigned the board into a wheel. The start/end wasn't that important. I think this change will not change the concept, only the way how the user(s) can get the points. Thanks for the input!
