### ISSUE TITLE
#5 Buttons for create and delete

### ISSUE THREAD

**Issue by gaborrubus** [gaborrubus/capstone-project#7]
## Value proposition

As a user
I want to be able to add and delete an action item 
in order to create a new item, that adds to the list or delete an existing one from the list.

## Description

![image](https://user-images.githubusercontent.com/125888791/233323673-33ccfdfe-cb0b-4648-920f-048d3eaf88c2.png)

## Acceptance criteria

- [ ]"+" button on the action item list leads to the add action item page
- [ ]"ADD" button on the add action item page leads back to the action item list page and adds the new item to the list

- [ ] "Delete" button
- [ ] criteria 2

## Tasks

- [ ] the "+" button should
- [ ] task 2

Size:

**Comment by CJAkkuec** [comment]
My bad, if I'd seen this earlier I'd probably have advised you to split this into two user stories. Creating and deleting are two entirely separate feature functionalities, so they're two separate user stories.
