### ISSUE TITLE
#6 Edit an action item on the list

### ISSUE THREAD

**Issue by gaborrubus** [gaborrubus/capstone-project#8]
## Value proposition

As a user
I want to be able to edit an action item
in order to personalize/change an item.

## Description

![image](https://user-images.githubusercontent.com/125888791/233645933-79953ca6-6c2f-48b6-80c6-bdc826cd1a0d.png)

## Acceptance criteria

- [ ] Visible Edit button, giving the ability to modify the form, by pushing the edit button, the form input fields are focusing on the input value (select all or blinking cursor)
- [ ] Save button saves the changes and leads back to the list page.
- [ ] Back buttons directing back to the action item list page.

## Tasks

- [ ] Input fields of the form (title, points, description) can be changed.
- [ ] With input focus value, make the user visible that the text is editable.
- [ ] Back button pushes back to the action item list without saving any changes

Size: S

**Comment by onemanwenttomow** [comment]
If the Del button does not do anything yet, i would remove it from the wireframe. 

Will the 3rd screen (i.e. the one with the Save button on) be showing input fields? At the moment this is not clear from the wireframes. Will the second screen be displaying the content (i.e. in divs vs inputs?)

How can i go back to the first screen from the second (without clicking on Edit?). Does it make sense to include a back button here too?

**Comment by CJAkkuec** [comment]
I think the sneaky delete button has made it through the changes unscathed. ;)

**Comment by gaborrubus** [comment]
I have updated the text and the wireframe. The Del button has the function of deleting an action item from the list. Included in [US 5](https://github.com/gaborrubus/capstone-project/issues/7)
